### Напишем функции для вычисления расстояния Хэмминга и числа попарных совпадений координат

In [1]:
import numpy as np
def hamming_distance(a, b):
    if len(a) != len(a):
        print("Invalid lens")
        return -1
    dist = 0
    for x, y in zip(a, b):
        if x != y:
            dist += 1
    return dist

def anti_hamming_distance(a, b):
    if len(a) != len(a):
        print("Invalid lens")
        return -1
    amount = 0
    return len(a) - hamming_distance(a, b)

### Напишем функции, которые формируют матрицы попарных расстояний Хэммигна и попарного числа совпадений координат.

In [2]:
def create_hamming_distance_matrix(a):
    """a - list of vectors"""
    if len(a) < 0:
        print("Not enough vectors.")
        return -1
    vectors_amount = len(a)
    matrix = np.zeros((vectors_amount, vectors_amount))
    for i in range(vectors_amount):
        for j in range(vectors_amount):
            matrix[i][j] = hamming_distance(a[i], a[j])
    return matrix
    

In [3]:
def create_anti_hamming_distance_matrix(a):
    """a - list of vectors"""
    vectors_amount = len(a)
    vectors_dim = len(a[0])
    hamming_matrix = create_hamming_distance_matrix(a)
    return abs(vectors_dim * np.ones(vectors_amount) - hamming_matrix)

### Напишем функцию для генерации векторов одинаковой длины:

In [4]:
def generate_vectors(vectors_amount, vectors_dim, coordinates_range, seed):
    if seed != None:
        np.random.seed = seed
    vectors = []
    i = 0
    while i < vectors_amount:
        flag = 1
        vector = np.random.randint(coordinates_range, size=(vectors_dim))
        for vec in vectors:
            matches_number = np.sum(np.equal(vector, vec))
            if matches_number == vectors_dim:
                flag = 0
                break
        if flag:
            vectors.append(vector)
            i += 1
    return vectors

### Проверим написанные функции:

In [5]:
vectors = generate_vectors(5, 4, 2, 6)
vectors

[array([0, 1, 0, 0]),
 array([0, 0, 0, 0]),
 array([0, 0, 0, 1]),
 array([1, 0, 0, 0]),
 array([0, 1, 1, 0])]

In [6]:
ham = create_hamming_distance_matrix(vectors)
ham

array([[0., 1., 2., 2., 1.],
       [1., 0., 1., 1., 2.],
       [2., 1., 0., 2., 3.],
       [2., 1., 2., 0., 3.],
       [1., 2., 3., 3., 0.]])

In [7]:
anti_ham = create_anti_hamming_distance_matrix(vectors)
anti_ham

array([[4., 3., 2., 2., 3.],
       [3., 4., 3., 3., 2.],
       [2., 3., 4., 2., 1.],
       [2., 3., 2., 4., 1.],
       [3., 2., 1., 1., 4.]])

## Напишем функцию, проверяющую первую гипотезу из отчета.

In [86]:
def first_hypothesis_vect_cycle(vectors_amount=15, vectors_dim=5, coordinates_range=3, seed=0, file=0):
    for i in range(vectors_amount):
        vectors = generate_vectors(i+2, vectors_dim, coordinates_range+i, seed)
        ham = create_hamming_distance_matrix(vectors)
        anti_ham = create_anti_hamming_distance_matrix(vectors)
        ham_rank = np.linalg.matrix_rank(ham)
        anti_ham_rank = np.linalg.matrix_rank(anti_ham)
        concat_matrix = np.concatenate((ham, anti_ham), axis = -1)
        concat_matrix_rank = np.linalg.matrix_rank(concat_matrix)
        if ((concat_matrix_rank == ham_rank) & (concat_matrix_rank == anti_ham_rank)):
            print("Vectors amount: ", i+2, file=file)
            print("Vectors dim: ", vectors_dim, file=file)
            print("Coordinates range: ", coordinates_range+i, file=file)
            print("________________________________", file=file)
        else: 
            print("********************************************", file=file)
            print("Bad", file=file)
            print("Vectors: ", vectors, file=file)
            print("ham:\n", ham, file=file)
            print("anti-ham:\n", anti_ham, file=file)
            print("Vectors amount: ", i+2, file=file)
            print("*********************************************", file=file)
    return 0

In [87]:
def first_hypothesis_check(vectors_amount=15, vectors_dim=15, coordinates_range=15, seed=0):
    with open("first_hypothesis_check", "w") as file:
        for i in range(1, vectors_dim):
            for j in range(4, coordinates_range):
                first_hypothesis_vect_cycle(vectors_amount=vectors_amount, 
                                                vectors_dim=i, coordinates_range=j, seed=seed, file=file)

In [90]:
first_hypothesis_check(vectors_amount = 100, vectors_dim=6, coordinates_range = 5, seed=15)

### По результатам работы функции замечаем, что ответ на вопрос задачи отрицательный, если в выборке векторов есть хотя бы два совпадающих. Иначе - ответ положительный. 

## Гипотеза: верно, что пространства линейных комбинаций столбцов данных матриц совпадают.

## Попробуем посмотреть на различные характеристики матриц H и M:

In [28]:
def matrix_characteristics_0(vectors_amount=15, vectors_dim=5, coordinates_range=3, seed=0):
    with open("matrix_characteristics_0", "w") as file:
        for i in range(vectors_amount):
            vectors = generate_vectors(i+1, vectors_dim, coordinates_range, seed)
            ham = create_hamming_distance_matrix(vectors)
            anti_ham = create_anti_hamming_distance_matrix(vectors)
            print("Ham = \n{}".format(ham), file=file)
            print("Anti_Ham = \n{}".format(anti_ham), file=file)
            print("vectors = \n{}".format(vectors), file=file)
            print("|Ham|      = {}".format(np.linalg.matrix_rank(ham)), file=file)
            print("|Anti_Ham| = {}".format(np.linalg.matrix_rank(anti_ham)), file=file)

In [29]:
matrix_characteristics_0(vectors_amount=100, vectors_dim=5, coordinates_range=4, seed = 235)

In [30]:
def matrix_characteristics_1(vectors_amount=15, vectors_dim=5, coordinates_range=3, seed=0):
    with open("matrix_characteristics_1", "w") as file:
        for i in range(vectors_amount):
            vectors = generate_vectors(i+1, vectors_dim, coordinates_range, seed)
            ham = create_hamming_distance_matrix(vectors)
            anti_ham = create_anti_hamming_distance_matrix(vectors)
            power = 10
            powered_ham = np.linalg.matrix_power(ham, power)
            powered_anti_ham = np.linalg.matrix_power(anti_ham, power)
            print("Powered_Ham_rank      = {}".format(np.linalg.matrix_rank(powered_ham)), file = file)
            print("Powered_Anti_Ham_rank = {}".format(np.linalg.matrix_rank(powered_anti_ham)), file = file)

In [31]:
matrix_characteristics_1(vectors_amount=200, coordinates_range=9, seed=20)

In [34]:
def matrix_characteristics_2(vectors_amount=15, vectors_dim=5, coordinates_range=3, seed=0):
    with open("matrix_characteristics_2", "w") as file:
        for i in range(vectors_amount):
            vectors = generate_vectors(i+1, vectors_dim, coordinates_range, seed)
            ham = create_hamming_distance_matrix(vectors)
            anti_ham = create_anti_hamming_distance_matrix(vectors)
#             concat_matrix = np.concatenate((ham, anti_ham), axis = -1)
#             concat_matrix_rank = np.linalg.matrix_rank(concat_matrix)
#             print("Ham = \n{}".format(ham))
#             print("Anti_Ham = \n{}".format(anti_ham))
#             print("vectors = \n{}".format(vectors))
            ham_singular_vals = np.linalg.svd(ham)[1]
            anti_ham_singular_vals = np.linalg.svd(anti_ham)[1]
            print("Ham_sing      = {}".format(ham_singular_vals), file = file)
            print("Anti_Ham_sing = {}".format(anti_ham_singular_vals), file = file)
            print(np.mean(ham_singular_vals-anti_ham_singular_vals), file = file)
            print("____________________________________________", file = file)

In [35]:
matrix_characteristics_2(vectors_amount= 100)

## Попробуем найти зависимость у решений уравнения Hx = e, где e = (1, 1, 1, ..., 1)^T.

In [44]:
def second_hypothesis_check(vectors_amount=15, vectors_dim=5, coordinates_range=5, seed=0):
    with open("second_hypothesis_check_2", "w") as file:
        for i in range(vectors_amount):
                vectors = generate_vectors(i+2, vectors_dim, coordinates_range, seed)
                ham = create_hamming_distance_matrix(vectors)
                anti_ham = create_anti_hamming_distance_matrix(vectors)
                eye_vector = np.ones((i+2, 1))
                concat_matrix = np.concatenate((ham, eye_vector), axis = 1)
                print("Vectors amount: ", i+2, file = file)
                print("Ham: \n", ham, file = file)
                if (np.linalg.det(ham) != 0):
                    print("Solution:\n", (np.linalg.solve(ham, eye_vector)), " ", np.max(np.linalg.solve(ham, eye_vector)), file = file)
                else:
                    rank_ham = np.linalg.matrix_rank(ham)
                    rank_aug = np.linalg.matrix_rank(concat_matrix)
                    if rank_ham != rank_aug:
                        print("***************************Теорема Кронекера-Капелли не выполняется!**********************************", file = file)
                    else:
                        print("Теорема Кронекера-Капелли выполняется => система имеет бесконечно много решений", file = file)
                print("______________________________________________________________", file = file)

## Как видим из результатов - нужно учитывать, что гипотеза 2 должна быть верна(проверена при различных параметрах vectors_amount, vectors_dim, coordinates_range).

In [37]:
for i in range(2, 50):
    second_hypothesis_check(i, vectors_dim = i, coordinates_range = i, seed=i)

In [41]:
for i in range(2, 50):
    second_hypothesis_check(vectors_amount=i, vectors_dim = 1, coordinates_range=50000, seed = i)

In [46]:
for i in range(2, 50):
    second_hypothesis_check(vectors_amount=i, vectors_dim = 5, coordinates_range=15, seed = i)

In [47]:
def second_hypothesis_check_anti_ham(vectors_amount=15, vectors_dim=5, coordinates_range=5, seed=0):
    with open("second_hypothesis_check_anti_ham", "w") as file:
        for i in range(vectors_amount):
            vectors = generate_vectors(i+2, vectors_dim, coordinates_range, seed)
            ham = create_hamming_distance_matrix(vectors)
            anti_ham = create_anti_hamming_distance_matrix(vectors)
            eye_vector = np.ones((i+2, 1))
            concat_matrix = np.concatenate((anti_ham, eye_vector), axis = 1)
            print("Vectors amount: ", i+2, file = file)
            print("Anti-Ham: \n", anti_ham, file = file)
            if (np.linalg.det(anti_ham) != 0):
                print("Solution:\n", (np.linalg.solve(anti_ham, eye_vector)), " ", np.max(np.linalg.solve(anti_ham, eye_vector)), file = file)
            else:
                rank_anti_ham = np.linalg.matrix_rank(anti_ham)
                rank_aug = np.linalg.matrix_rank(concat_matrix)
                if rank_anti_ham != rank_aug:
                    print("***************************Теорема Кронекера-Капелли не выполняется!**********************************", file = file)
                else:
                    print("Теорема Кронекера-Капелли выполняется => система имеет бесконечно много решений", file = file)
            print("______________________________________________________________", file = file)

In [48]:
second_hypothesis_check_anti_ham(vectors_amount=20, vectors_dim=2, coordinates_range=19)